version: 0.2
env:
  variables:
    APP_NAME: "aws-cicd-simple"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=development
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://dev-archfacts-build --delete
